version: "3.7"

services:
  app:
    build:
      context: ./src

    # command: guicorn config.wsgi.application --bind 0.0.0.0:8000
    working_dir: /usr/src/app/
    volumes:
      - ./src:/usr/src/app
      - static_volume:/usr/src/app/staticfiles
      - media_volume:/usr/src/app/mediafiles
    expose: 
      - 8000
    env_file:
      - ./.env
    depends_on:
      - postgres
    networks:
      - front
      - back
    tty: true

  postgres:
    image: postgres:12.0-alpine
    volumes:
      - db_data:/var/lib/postgresql/data
    env_file:
      - ./.env
    networks:
      - back

  nginx:
    build:
      context: ./nginx
    volumes:
      - static_volume:/usr/src/app/staticfiles
      - media_volume:/usr/src/app/mediafiles
    ports:
      - 8888:80
    depends_on:
      - app
    networks:
      - front

volumes:
  db_data:
  static_volume:
  media_volume:

networks:
  front:
    external: false
  back:
    external: false
